
%% 0) Clean All Project Output Folders
% -------------------------------------------------------------------------
% PURPOSE:
% This utility script deletes all generated output folders from the road
% profile reconstruction pipeline. It is used to ensure a completely fresh
% start for a new run.
%
% WARNING: This script will permanently delete data.
% -------------------------------------------------------------------------

close all; clc;

% --- List of all output folders to be deleted ---
% This list should contain the names of all folders generated by your pipeline.
folders_to_delete = {
    '00_Outputs'
};

% --- Confirmation Prompt ---
fprintf('This script will permanently delete the following %d folders and all their contents:\n', numel(folders_to_delete));
for i = 1 : numel(folders_to_delete)
    fprintf('- %s\n', folders_to_delete{i});
end
fprintf('\n');

% Ask for user confirmation
response = input('Are you sure you want to proceed? [y/n]: ', 's');

% --- Deletion Logic ---
% Only proceed if the user explicitly types 'y' or 'Y'
if strcmpi(response, 'y')
    fprintf('\nProceeding with deletion...\n');
    
    deleted_count = 0;
    not_found_count = 0;
    
    for i = 1:numel(folders_to_delete)
        folder_name = folders_to_delete{i};
        
        % Check if the item exists and is a directory
        if exist(folder_name, 'dir')
            try
                % Delete the directory and all its contents ('s' flag)
                rmdir(folder_name, 's');
                fprintf('Deleted: %s\n', folder_name);
                deleted_count = deleted_count + 1;
            catch
                fprintf('ERROR: Could not delete %s. Reason: %s\n', folder_name);
            end
        else
            fprintf('Not found (skipping): %s\n', folder_name);
            not_found_count = not_found_count + 1;
        end
    end
    
    fprintf('\nCleanup complete. %d folders deleted, %d not found.\n', deleted_count, not_found_count);
    
else
    fprintf('\nOperation cancelled by user. No folders were deleted.\n');
end